# Workflow 이름
name: Spring Boot & Gradle CI/CD

on:
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # JDK 17 설치
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    # github secret 환경변수로 적어둔 APPLICATION_PROPERTIES으로 application.yml파일을 생성합니다.
    # 환경변수가 지나치게 많아짐을 방지하기 위해 APPLICATION_PROPERTIES 변수를 만들었습니다.
    - name: make application.yml
      run: |
        echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml
      shell: bash
      
    # gradlew에 실행 권한을 부여합니다.
    - name: Grant execute permisson for gradlew
      run: chmod +x gradlew
 
      # test는 CI 과정에서 수행되므로 여기서는 `-x`로 테스트를 생략했습니다.
      # `--stacktrace`로 더 자세한 로그가 출력되게 해줍니다.
    - name: Build with Gradle (without Test)
      run: ./gradlew clean build -x test --stacktrace
 
      # docker hub에 로그인하고 이미지를 빌드합니다. 이후에 push를 진행합니다.
      # docker_username을 적지 않으면 push 시에 요청이 거부될 수 있습니다.
    - name: Docker Hub build & push
      run: |
          # docker login -u docteory07 -p ${{ secrets.DOCKER_PASSWORD }}
          # docker build -t docteory07/${{ secrets.DOCKER_REPO }} .
          # docker push docteory07/${{ secrets.DOCKER_REPO }}
 
      # EC2에 접속하고 배포합니다.
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          port: 22

          script: |
              cd /home/ec2-user/server # 프로젝트 위치
              git pull origin main              # 최신 코드 가져오기
              ./gradlew clean build -x test
              sudo docker build -t audion .
              sudo docker rm -f audion
              sudo docker run -d --name audion -p 8080:8080 --restart unless-stopped audion
